[build.environment]
  NPM_FLAGS = "--version"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[plugins]]
  package = "netlify-plugin-cache-folder"